export const AAA_GAMES = [
  {
    name: "The Last of Us Part II",
    image:
      "https://static-cdn.jtvnw.net/ttv-boxart/The%20Last%20of%20Us%20Part%20II.jpg",
  },
  {
    name: "Cyberpunk 2077",
    image: "https://static-cdn.jtvnw.net/ttv-boxart/Cyberpunk%202077.jpg",
  },
  {
    name: "Red Dead Redemption 2",
    image:
      "https://static-cdn.jtvnw.net/ttv-boxart/Red%20Dead%20Redemption%202.jpg",
  },
  {
    name: "Ghost of Tsushima",
    image: "https://static-cdn.jtvnw.net/ttv-boxart/Ghost%20of%20Tsushima.jpg",
  },
  {
    name: "God of War",
    image: "https://static-cdn.jtvnw.net/ttv-boxart/God%20of%20War.jpg",
  },
  {
    name: "The Witcher 3: Wild Hunt",
    image:
      "https://static-cdn.jtvnw.net/ttv-boxart/The%20Witcher%203:%20Wild%20Hunt.jpg",
  },
];

export const data = [
  {
    id: "217245",
    name: "2v2 OCCUPY KILL RACE BEST OF 1",
    backgroundUrl: "/theme/cmg2/src/images/default-team-banner.jpg",
    coverUrl:
      "https://www.checkmategaming.com/images/ladders/1681498266125.png",
    platformImageUrl:
      "https://www.checkmategaming.com/images/platforms/crossplatform.png",
    groupImageUrl:
      "https://www.checkmategaming.com/images/ladders/1681498266552.png",
    groupName: "XDefiant",
    groupUrl:
      "https://www.checkmategaming.com/tournament/cross-platform/xdefiant",
    platformShortName: "crossplatform",
    platformName: "Cross-Platform",
    platformId: 8,
    gameId: 62,
    gameImageUrl:
      "https://www.checkmategaming.com/images/ladders/1681498266552.png",
    gameName: "XDefiant",
    gameShortName: "XDefiant",
    gameOrderPriority: "148",
    platformOrderPriority: 100,
    teamSize: "2v2",
    cost: "5",
    prize: 180,
    prizeDescription: "",
    tournamentPath:
      "/tournament/cross-platform/xdefiant/2v2-occupy-kill-race-best-of-1-217245",
    tournamentName: "2v2 OCCUPY KILL RACE BEST OF 1",
    registrationTime: "Jan 1st |1:00 AM EST",
    startTime: "Jul 18th |7:30 PM EDT",
    startTimestamp: 1721345400,
    startTimeDay: "Jul 18",
    startTimeHour: "7:30 pm EDT",
    regions_names: ["NA + EU"],
    is_premium: "0",
    is_guaranteed: false,
    is_global: false,
    is_na_eu: true,
    is_na: false,
    is_eu: false,
    is_apac: false,
    is_latam: false,
    is_amateur: false,
    is_hidden: false,
    hide_prize: false,
    kd_cap: "0.00",
    elo_levels: [0, 1, 2],
    beginTimestamp: 1721345400,
    enrolledTeamsCount: 0,
    canMemberJoin: false,
    canMemberSetTournamentReminder: false,
    isReminderSet: false,
    entryString: "5 Credits",
  },
  {
    id: "217246",
    name: "2v2 OCCUPY KILL RACE BEST OF 1",
    backgroundUrl: "/theme/cmg2/src/images/default-team-banner.jpg",
    coverUrl:
      "https://www.checkmategaming.com/images/ladders/1681498266125.png",
    platformImageUrl:
      "https://www.checkmategaming.com/images/platforms/crossplatform.png",
    groupImageUrl:
      "https://www.checkmategaming.com/images/ladders/1681498266552.png",
    groupName: "XDefiant",
    groupUrl:
      "https://www.checkmategaming.com/tournament/cross-platform/xdefiant",
    platformShortName: "crossplatform",
    platformName: "Cross-Platform",
    platformId: 8,
    gameId: 62,
    gameImageUrl:
      "https://www.checkmategaming.com/images/ladders/1681498266552.png",
    gameName: "XDefiant",
    gameShortName: "XDefiant",
    gameOrderPriority: "148",
    platformOrderPriority: 100,
    teamSize: "2v2",
    cost: "5",
    prize: 180,
    prizeDescription: "",
    tournamentPath:
      "/tournament/cross-platform/xdefiant/2v2-occupy-kill-race-best-of-1-217246",
    tournamentName: "2v2 OCCUPY KILL RACE BEST OF 1",
    registrationTime: "Jan 1st |1:00 AM EST",
    startTime: "Jul 19th |7:30 PM EDT",
    startTimestamp: 1721431800,
    startTimeDay: "Jul 19",
    startTimeHour: "7:30 pm EDT",
    regions_names: ["NA + EU"],
    is_premium: "0",
    is_guaranteed: false,
    is_global: false,
    is_na_eu: true,
    is_na: false,
    is_eu: false,
    is_apac: false,
    is_latam: false,
    is_amateur: false,
    is_hidden: false,
    hide_prize: false,
    kd_cap: "0.00",
    elo_levels: [0, 1, 2],
    beginTimestamp: 1721431800,
    enrolledTeamsCount: 0,
    canMemberJoin: false,
    canMemberSetTournamentReminder: false,
    isReminderSet: false,
    entryString: "5 Credits",
  },
  {
    id: "217247",
    name: "2v2 OCCUPY KILL RACE BEST OF 1",
    backgroundUrl: "/theme/cmg2/src/images/default-team-banner.jpg",
    coverUrl:
      "https://www.checkmategaming.com/images/ladders/1681498266125.png",
    platformImageUrl:
      "https://www.checkmategaming.com/images/platforms/crossplatform.png",
    groupImageUrl:
      "https://www.checkmategaming.com/images/ladders/1681498266552.png",
    groupName: "XDefiant",
    groupUrl:
      "https://www.checkmategaming.com/tournament/cross-platform/xdefiant",
    platformShortName: "crossplatform",
    platformName: "Cross-Platform",
    platformId: 8,
    gameId: 62,
    gameImageUrl:
      "https://www.checkmategaming.com/images/ladders/1681498266552.png",
    gameName: "XDefiant",
    gameShortName: "XDefiant",
    gameOrderPriority: "148",
    platformOrderPriority: 100,
    teamSize: "2v2",
    cost: "5",
    prize: 180,
    prizeDescription: "",
    tournamentPath:
      "/tournament/cross-platform/xdefiant/2v2-occupy-kill-race-best-of-1-217247",
    tournamentName: "2v2 OCCUPY KILL RACE BEST OF 1",
    registrationTime: "Jan 1st |1:00 AM EST",
    startTime: "Jul 20th |7:30 PM EDT",
    startTimestamp: 1721518200,
    startTimeDay: "Jul 20",
    startTimeHour: "7:30 pm EDT",
    regions_names: ["NA + EU"],
    is_premium: "0",
    is_guaranteed: false,
    is_global: false,
    is_na_eu: true,
    is_na: false,
    is_eu: false,
    is_apac: false,
    is_latam: false,
    is_amateur: false,
    is_hidden: false,
    hide_prize: false,
    kd_cap: "0.00",
    elo_levels: [0, 1, 2],
    beginTimestamp: 1721518200,
    enrolledTeamsCount: 0,
    canMemberJoin: false,
    canMemberSetTournamentReminder: false,
    isReminderSet: false,
    entryString: "5 Credits",
  },
  {
    id: "217248",
    name: "2v2 OCCUPY KILL RACE BEST OF 1",
    backgroundUrl: "/theme/cmg2/src/images/default-team-banner.jpg",
    coverUrl:
      "https://www.checkmategaming.com/images/ladders/1681498266125.png",
    platformImageUrl:
      "https://www.checkmategaming.com/images/platforms/crossplatform.png",
    groupImageUrl:
      "https://www.checkmategaming.com/images/ladders/1681498266552.png",
    groupName: "XDefiant",
    groupUrl:
      "https://www.checkmategaming.com/tournament/cross-platform/xdefiant",
    platformShortName: "crossplatform",
    platformName: "Cross-Platform",
    platformId: 8,
    gameId: 62,
    gameImageUrl:
      "https://www.checkmategaming.com/images/ladders/1681498266552.png",
    gameName: "XDefiant",
    gameShortName: "XDefiant",
    gameOrderPriority: "148",
    platformOrderPriority: 100,
    teamSize: "2v2",
    cost: "5",
    prize: 180,
    prizeDescription: "",
    tournamentPath:
      "/tournament/cross-platform/xdefiant/2v2-occupy-kill-race-best-of-1-217248",
    tournamentName: "2v2 OCCUPY KILL RACE BEST OF 1",
    registrationTime: "Jan 1st |1:00 AM EST",
    startTime: "Jul 21st |7:30 PM EDT",
    startTimestamp: 1721604600,
    startTimeDay: "Jul 21",
    startTimeHour: "7:30 pm EDT",
    regions_names: ["NA + EU"],
    is_premium: "0",
    is_guaranteed: false,
    is_global: false,
    is_na_eu: true,
    is_na: false,
    is_eu: false,
    is_apac: false,
    is_latam: false,
    is_amateur: false,
    is_hidden: false,
    hide_prize: false,
    kd_cap: "0.00",
    elo_levels: [0, 1, 2],
    beginTimestamp: 1721604600,
    enrolledTeamsCount: 0,
    canMemberJoin: false,
    canMemberSetTournamentReminder: false,
    isReminderSet: false,
    entryString: "5 Credits",
  },
];
// export const AAA_GAMES = [
//   {
//     name: "The Last of Us Part II",
//     image:
//       "https://static-cdn.jtvnw.net/ttv-boxart/The%20Last%20of%20Us%20Part%20II.jpg",
//   },
//   {
//     name: "Cyberpunk 2077",
//     image: "https://static-cdn.jtvnw.net/ttv-boxart/Cyberpunk%202077.jpg",
//   },
//   {
//     name: "Red Dead Redemption 2",
//     image:
//       "https://static-cdn.jtvnw.net/ttv-boxart/Red%20Dead%20Redemption%202.jpg",
//   },
//   {
//     name: "Ghost of Tsushima",
//     image: "https://static-cdn.jtvnw.net/ttv-boxart/Ghost%20of%20Tsushima.jpg",
//   },
//   {
//     name: "Fortnite",
//     image: "https://static-cdn.jtvnw.net/ttv-boxart/Fortnite.jpg",
//   },
//   {
//     name: "Call of Duty: Modern Warfare",
//     image:
//       "https://static-cdn.jtvnw.net/ttv-boxart/Call%20of%20Duty:%20Modern%20Warfare.jpg",
//   },
// ];
